/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layouts;

import static Layouts.RegistroLayout.getHash;
import civerlac.Cliente;
import civerlac.ConexionSQL;
import civerlac.DatosEmpresa;
import civerlac.ErrorLogs;
import civerlac.Login;
import civerlac.LoginDB;
import civerlac.ProductoDB;
import civerlac.producto;
import civerlac.valoresEstaticos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Omaly Breve
 */
public class LoginLayout extends javax.swing.JFrame {

    Login lg = new Login();
    LoginDB login = new LoginDB();
    String user = new String();
    String pass = new String();

    /**
     * Creates new form Login
     */
    public LoginLayout() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/LOGO.png")).getImage());
        this.setLocationRelativeTo(null);
        testencription();
         this.setTitle("Login"); 

    }
    ErrorLogs el = new ErrorLogs();// instancia de la clase error log
    //los logs se generan donde vos queras que se capture ingormacion
    //la funcion solo espera un parametro, el mensaje
    // normalmente los logs van dentro de los try catch, donde vas guardando los logs de los registros
    // vamos al try catch de el boton login
    public void validar() {
        user = txtUsuario.getText();
        pass = String.valueOf(txtContrasena.getPassword());

        if (!"".equals(user) || !"".equals(pass)) {

            lg = login.log(user, pass);

            if (lg.getUser() != null && lg.getPass() != null) {
                Sistema sis = new Sistema();
                sis.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o Contrasena incorrectos");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar sesión");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtContrasena.setForeground(new java.awt.Color(51, 51, 51));
        txtContrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/contraseña del login.png"))); // NOI18N
        jLabel1.setText("Contraseña");

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario del login.png"))); // NOI18N
        jLabel3.setText("Usuario");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LOGO MEDIANO.png"))); // NOI18N

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("By: CiverlacTeam©");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel57)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Encriptacion de las contrasenas
    public void testencription() {
        String clave = "123456789";
        String tipohash = "MD5";

        getHash(clave, tipohash);

        System.out.println(getHash(clave, tipohash));

    }

        // si el try catch dice static, no lo va reconocer
    public static String getHash(String txt, String hashType) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest
                    .getInstance(hashType);
            byte[] array = md.digest(txt.getBytes());
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < array.length; ++i) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100)
                        .substring(1, 3));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            System.out.println(e.getMessage());
            
        }
        return null;
    }
    int intentos = 0;
    String state = null;
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        
        java.util.Date fecha = new java.util.Date();
        DateFormat f = new SimpleDateFormat("dd/MM/yyyy hh");
        String fechaActual = f.format(fecha);
        String userLog = "";

        String clave = txtContrasena.getText();
        String Usuario = txtUsuario.getText();

        valoresEstaticos vals = new valoresEstaticos();

        ConexionSQL cn = new ConexionSQL();
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "SELECT * from empleado where correo=?";

        double cantidad;
        if (txtUsuario.getText().length() > 3 && txtContrasena.getText().length() > 3) {

            if (txtUsuario.getText().length() < 26 && txtContrasena.getText().length() < 26) {
                try {
                    
                    con = cn.getConnection();// asui se genra la conexion, si todo salio bien// quiero ese log
                    // me voy al final a hacerlo
                    ps = con.prepareStatement(sql);
                    if (txtUsuario.getText() != "" && txtUsuario.getText().contains("@")) {
                        if (txtUsuario.getText().contains("gmail.com") || txtUsuario.getText().contains("yahoo.com")
                                || txtUsuario.getText().contains("hotmail.com")) {
                            ps.setString(1, txtUsuario.getText());
                            //ps.setString(2, txtContrasena.getText());
                            rs = ps.executeQuery();
                            if (rs.next()) {
                                String sql2 = "SELECT * from `empleado` where correo=?";
                                ps = con.prepareStatement(sql2);
                                ps.setString(1, txtUsuario.getText().toString().trim());
                                rs = ps.executeQuery();
                                rs.next();
                                userLog = rs.getString("idEmpleado");
                                int estat = rs.getInt("Estado");

                                int valido = 1;
                                String correo = txtUsuario.getText();
                                if (estat == valido) {

                                    if (intentos < 3) {

                                        intentos++;
                                        String Password = getHash(txtContrasena.getText().trim(), "MD5");
                                        String sql3 = "SELECT  b.correo,b.Nombre,a.clave,a.idUsuario,a.privilegio  from EmpleadoUsuario AS a JOIN empleado as b on a.idUsuario=b.idEmpleado where b.correo=? and a.clave=?";
                                        ps = con.prepareStatement(sql3);
                                        ps.setString(1, txtUsuario.getText().trim());
                                        ps.setString(2, Password);
                                        rs = ps.executeQuery();

                                        if (rs.next()) {

                                            JOptionPane.showMessageDialog(null, "Bienvenido al sistema Civerlac");
                                            userLog = (rs.getString("idUsuario"));
                                            vals.setUsuario(rs.getString("Nombre"));
                                            vals.setIdUsuario(rs.getInt("idUsuario"));
                                            vals.setPrivilegio(rs.getInt("privilegio"));
                                            Sistema sistem = new Sistema();
                                            sistem.setPrivilegioUser(vals.getPrivilegio());
                                            new Sistema().setVisible(true);
                                            el.LogBitacora("El usuario " + userLog + vals.getUsuario() + "ingreso al sistema");
                                            
                                            dispose();
                                        } else if (intentos == 3) {
                                              LoginDB lg = new LoginDB();
                                            if(state == "reStart"){
                                          
                                                lg.updateLogLogin("3");
                                            }
                                            JOptionPane.showMessageDialog(null, "Usuario bloqueado por limite de intentos, contacte con un administrador");
                                            String sql4 = "Update empleado set Estado=2 where Correo=?";
                                            ps = con.prepareStatement(sql4);
                                            ps.setString(1, txtUsuario.getText().trim());
                                            ps.executeUpdate();
                                            el.LogBitacora("El usuario " + txtUsuario.getText() + "fue bloqueado por limite de intentos");
                                            System.exit(0);
                                        } else if (intentos == 2) {
                                            LoginDB lg = new LoginDB();
                                            if(state == "start"){
                                                state = "reStart";
                                                lg.updateLogLogin("2");
                                            }
                                             el.LogBitacora("El usuario " + txtUsuario.getText() + "lleva 2 intentos");
                                            JOptionPane.showMessageDialog(null, "Clave incorrecta, le queda 1 intento", "Error", JOptionPane.WARNING_MESSAGE);
                                        } else if (intentos == 1) {
                                            state = "start";
                                            LoginDB lg = new LoginDB();
                                            lg.registroLogLogin(fechaActual, userLog, "1");
                                            JOptionPane.showMessageDialog(null, "Clave incorrecta, le quedan 2 intentos", "Error", JOptionPane.WARNING_MESSAGE);
                                             el.LogBitacora("El usuario " + txtUsuario.getText() + "lleva 1 intento");
                                        }
                                       
                                    }
                                    /// 
                                    el.LogBitacora("Conexion Exitosa al servidor de datos"); // el es la instancia de la clase ErrorLog, LogBitacora es el metodo
                                    // y adentro esta el mensaje, probemos
                                } else {
                                    JOptionPane.showMessageDialog(null, "El usuario no esta habilitado", "Error", JOptionPane.WARNING_MESSAGE);
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "El usuario no existe", "Error", JOptionPane.ERROR_MESSAGE);

                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Debe insertar una extensión de correo válida \n"
                                    + "Ejemplo: civerlac@gmail.com",
                                    "Error", JOptionPane.WARNING_MESSAGE);

                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe insertar una extensión de correo válida \n"
                                + "Ejemplo: civerlac@gmail.com",
                                "Error", JOptionPane.WARNING_MESSAGE);

                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.toString());

                }

            } else {
                JOptionPane.showMessageDialog(null, "Hay campos con mas de 15 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Hay campos con menos de 8 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        //validar();
    }//GEN-LAST:event_btnLoginMouseClicked
    String correo = "";
    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped


    }//GEN-LAST:event_txtUsuarioKeyTyped
    String LetraActual;
    String Str;
    String correo2;
    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        // TODO add your handling code here:
        correo = txtUsuario.getText();
        LetraActual = correo.substring(0, correo.length() - 1);
        if (correo.chars()
                .boxed()
                .collect(Collectors.groupingBy(i -> i, Collectors.counting()))
                .values()
                .stream()
                .anyMatch(i -> i > 3)) {

        } else {

        }

    }//GEN-LAST:event_txtUsuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
