/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layouts;

import civerlac.ConexionSQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Omaly Breve
 */
public class UserSecurity extends javax.swing.JFrame {

    /**
     * Creates new form UserSecurity
     */
    public UserSecurity() {
        initComponents();
        getContentPane().setBackground(new Color(0,153,153));
        this.setLocationRelativeTo(null);
        jTabbedPane1.setEnabled(false);
        jTabbedPane1.setSelectedIndex(6);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
    }
    //estado de permisos
    //clientes
    String stClienteListar = "2";
    String stClienteIngresa = "4";
    String stClienteModificar = "7";
    String stClienteBuscar = "9";
    //proveedores
    String stProveedorListar = "2";
    String stProveedorIngresa = "4";
    String stProveedorModificar = "7";
    String stProveedorBuscar = "9";
    //empleados
    String stEmpleadoListar = "2";
    String stEmpleadoIngresa = "4";
    String stEmpleadoModificar = "7";
    String stEmpleadoBuscar = "9";
    String stEmpleadoAddUser = "3";
    //producto
    String stProdListar = "2";
    String stProdIngresa = "4";
    String stProdModificar = "7";
    String stProdEliminar = "9";
    /// Compra y Venta
    String stFVenta = "2";
    String stFHistorialVentas = "4";
    String stFHistorialFacturacion = "7";
    String stFCompra = "9";
    //Otros
    String stOconfiguracion = "2";
    String stOprecioHis = "4";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        ClienteBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblpuesto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnClistar = new javax.swing.JButton();
        btnCingresar = new javax.swing.JButton();
        btnCModificar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnCbusqueda = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnPlistar = new javax.swing.JButton();
        btnPingresar = new javax.swing.JButton();
        btnPmodificar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnPbusqueda = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnElistar = new javax.swing.JButton();
        btnEingresar = new javax.swing.JButton();
        btnEmodificar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnEbusqueda = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        btnAddusers = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnProListar = new javax.swing.JButton();
        btnProIngresar = new javax.swing.JButton();
        btnProModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnProdEliminar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnFacVenta = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        btnFacHv = new javax.swing.JButton();
        btnFacHf = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnFacCompra = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnOconfiguracion = new javax.swing.JButton();
        btnOprecioHis = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Email de el usuario");

        txtsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsearch.setText("omalybreve@gmail.com");
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        ClienteBuscar.setBackground(new java.awt.Color(0, 153, 153));
        ClienteBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClienteBuscar.setForeground(new java.awt.Color(255, 255, 255));
        ClienteBuscar.setText("Buscar");
        ClienteBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setText("Nombre");

        jLabel4.setText("Email");

        jLabel5.setText("Puesto");

        jLabel6.setText("Telefono");

        lblnombre.setText("-----------");

        lblemail.setText("-----------");

        lbltelefono.setText("-----------");

        lblpuesto.setText("-----------");

        jLabel14.setText("Codigo de regitro #:");

        lblid.setText("---------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbltelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblpuesto))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Permisos de Acceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setEnabled(false);

        btnClistar.setBackground(new java.awt.Color(0, 102, 51));
        btnClistar.setForeground(new java.awt.Color(255, 255, 255));
        btnClistar.setText("Activo");
        btnClistar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClistarActionPerformed(evt);
            }
        });

        btnCingresar.setBackground(new java.awt.Color(0, 102, 51));
        btnCingresar.setForeground(new java.awt.Color(255, 255, 255));
        btnCingresar.setText("Activo");
        btnCingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCingresarActionPerformed(evt);
            }
        });

        btnCModificar.setBackground(new java.awt.Color(0, 102, 51));
        btnCModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnCModificar.setText("Activo");
        btnCModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCModificarActionPerformed(evt);
            }
        });

        jLabel26.setText("Modificar Clientes");

        jLabel27.setText("Ingresar Clientes");

        jLabel28.setText("Listar Clientes");

        jLabel29.setText("Busqueda");

        btnCbusqueda.setBackground(new java.awt.Color(0, 102, 51));
        btnCbusqueda.setForeground(new java.awt.Color(255, 255, 255));
        btnCbusqueda.setText("Activo");
        btnCbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCbusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnClistar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(btnCbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(btnClistar)
                    .addComponent(jLabel29)
                    .addComponent(btnCbusqueda))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(btnCingresar))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(btnCModificar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnPlistar.setBackground(new java.awt.Color(0, 102, 51));
        btnPlistar.setForeground(new java.awt.Color(255, 255, 255));
        btnPlistar.setText("Activo");
        btnPlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlistarActionPerformed(evt);
            }
        });

        btnPingresar.setBackground(new java.awt.Color(0, 102, 51));
        btnPingresar.setForeground(new java.awt.Color(255, 255, 255));
        btnPingresar.setText("Activo");
        btnPingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPingresarActionPerformed(evt);
            }
        });

        btnPmodificar.setBackground(new java.awt.Color(0, 102, 51));
        btnPmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btnPmodificar.setText("Activo");
        btnPmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPmodificarActionPerformed(evt);
            }
        });

        jLabel20.setText("Modificar Proveedores");

        jLabel21.setText("Ingresar Provedores");

        jLabel22.setText("Listar Proveedores");

        jLabel30.setText("Busqueda");

        btnPbusqueda.setBackground(new java.awt.Color(0, 102, 51));
        btnPbusqueda.setForeground(new java.awt.Color(255, 255, 255));
        btnPbusqueda.setText("Activo");
        btnPbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPbusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnPingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnPmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(316, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(33, 33, 33)
                        .addComponent(btnPlistar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(btnPbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(btnPlistar)
                        .addComponent(jLabel30))
                    .addComponent(btnPbusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(btnPingresar))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(btnPmodificar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proveedores", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnElistar.setBackground(new java.awt.Color(0, 102, 51));
        btnElistar.setForeground(new java.awt.Color(255, 255, 255));
        btnElistar.setText("Activo");
        btnElistar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnElistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElistarActionPerformed(evt);
            }
        });

        btnEingresar.setBackground(new java.awt.Color(0, 102, 51));
        btnEingresar.setForeground(new java.awt.Color(255, 255, 255));
        btnEingresar.setText("Activo");
        btnEingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEingresarActionPerformed(evt);
            }
        });

        btnEmodificar.setBackground(new java.awt.Color(0, 102, 51));
        btnEmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btnEmodificar.setText("Activo");
        btnEmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmodificarActionPerformed(evt);
            }
        });

        jLabel23.setText("Modificar Empleados");

        jLabel24.setText("Ingresar Empleados");

        jLabel25.setText("Listar Empleados");

        jLabel31.setText("Busqueda");

        btnEbusqueda.setBackground(new java.awt.Color(0, 102, 51));
        btnEbusqueda.setForeground(new java.awt.Color(255, 255, 255));
        btnEbusqueda.setText("Activo");
        btnEbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEbusquedaActionPerformed(evt);
            }
        });

        jLabel32.setText("Agregar usuarios");

        btnAddusers.setBackground(new java.awt.Color(0, 102, 51));
        btnAddusers.setForeground(new java.awt.Color(255, 255, 255));
        btnAddusers.setText("Activo");
        btnAddusers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAddusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddusersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnEingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddusers, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(41, 41, 41)
                        .addComponent(btnElistar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(btnElistar)
                        .addComponent(jLabel31))
                    .addComponent(btnEbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(btnEingresar))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel32)
                        .addComponent(btnAddusers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(btnEmodificar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleados", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnProListar.setBackground(new java.awt.Color(0, 102, 51));
        btnProListar.setForeground(new java.awt.Color(255, 255, 255));
        btnProListar.setText("Activo");
        btnProListar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProListarActionPerformed(evt);
            }
        });

        btnProIngresar.setBackground(new java.awt.Color(0, 102, 51));
        btnProIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnProIngresar.setText("Activo");
        btnProIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProIngresarActionPerformed(evt);
            }
        });

        btnProModificar.setBackground(new java.awt.Color(0, 102, 51));
        btnProModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnProModificar.setText("Activo");
        btnProModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProModificarActionPerformed(evt);
            }
        });

        jLabel11.setText("Modificar Productos");

        jLabel12.setText("Ingresar Productos");

        jLabel13.setText("Listar Productos");

        btnProdEliminar.setBackground(new java.awt.Color(0, 102, 51));
        btnProdEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnProdEliminar.setText("Activo");
        btnProdEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdEliminarActionPerformed(evt);
            }
        });

        jLabel15.setText("Eliminar  Productos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnProListar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(26, 26, 26)))
                .addComponent(btnProdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnProdEliminar)
                    .addComponent(btnProListar)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnProIngresar))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnProModificar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel33.setText("Realizar Venta");

        btnFacVenta.setBackground(new java.awt.Color(0, 102, 51));
        btnFacVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnFacVenta.setText("Activo");
        btnFacVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFacVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacVentaActionPerformed(evt);
            }
        });

        jLabel34.setText("Historial venta");

        btnFacHv.setBackground(new java.awt.Color(0, 102, 51));
        btnFacHv.setForeground(new java.awt.Color(255, 255, 255));
        btnFacHv.setText("Activo");
        btnFacHv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFacHv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacHvActionPerformed(evt);
            }
        });

        btnFacHf.setBackground(new java.awt.Color(0, 102, 51));
        btnFacHf.setForeground(new java.awt.Color(255, 255, 255));
        btnFacHf.setText("Activo");
        btnFacHf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFacHf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacHfActionPerformed(evt);
            }
        });

        jLabel35.setText("Historial Fact.");

        jLabel36.setText("Realizar  Compra");

        btnFacCompra.setBackground(new java.awt.Color(0, 102, 51));
        btnFacCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnFacCompra.setText("Activo");
        btnFacCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFacCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(33, 33, 33)
                        .addComponent(btnFacVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel36)
                        .addGap(33, 33, 33)
                        .addComponent(btnFacCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(33, 33, 33)
                        .addComponent(btnFacHv, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(33, 33, 33)
                        .addComponent(btnFacHf, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(btnFacCompra))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(btnFacVenta)))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(btnFacHv))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(btnFacHf))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Compra & Venta", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        btnOconfiguracion.setBackground(new java.awt.Color(0, 102, 51));
        btnOconfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnOconfiguracion.setText("Activo");
        btnOconfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOconfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOconfiguracionActionPerformed(evt);
            }
        });

        btnOprecioHis.setBackground(new java.awt.Color(0, 102, 51));
        btnOprecioHis.setForeground(new java.awt.Color(255, 255, 255));
        btnOprecioHis.setText("Activo");
        btnOprecioHis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOprecioHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOprecioHisActionPerformed(evt);
            }
        });

        jLabel37.setText("Precio Historico");

        jLabel38.setText("Configuracion de negocio");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOprecioHis, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOconfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(btnOconfiguracion))
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(btnOprecioHis))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Otros", jPanel9);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Neceistas selecionar un usuario");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(138, 138, 138))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel7)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Not found", jPanel7);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Permisos de Seguridad");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(13, 13, 13)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(ClienteBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClienteBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchKeyReleased

    private void ClienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteBuscarActionPerformed
        // TODO add your handling code here:
        int idUser;
        ConexionSQL cn = new ConexionSQL();
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "Select  b.idEmpleado, b.Nombre,b.idTelefonoEmp,b.Correo, b.Ocupacion from `EmpleadoUsuario` as a\n"
                + "join empleado as b on a.idUsuario=b.idEmpleado where b.Correo = ? ";
        try {

            con = cn.getConnection();
            ps = con.prepareStatement(sql);
            ps.setString(1, txtsearch.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "El usuario ya existe");
                lblnombre.setText(rs.getString("Nombre"));
                lblemail.setText(rs.getString("correo"));
                lbltelefono.setText(rs.getString("idTelefonoEmp"));
                lblid.setText(rs.getString("idEmpleado"));
                lblpuesto.setText(rs.getString("Ocupacion"));
                jTabbedPane1.setEnabled(true);
                jTabbedPane1.setSelectedIndex(0);
                jTabbedPane1.setEnabledAt(6, false);
                jButton1.setEnabled(true);
                ClienteBuscar.setEnabled(false);
                jButton2.setEnabled(true);
                //
                con = null;
                ps = null;
                rs = null;
                String sql2 = "SELECT * FROM usuariopermiso where idUsuario = ? ";

                con = cn.getConnection();
                ps = con.prepareStatement(sql2);
                ps.setString(1, lblid.getText());
                rs = ps.executeQuery();
                if (rs.next()) {
                    System.out.println(rs.getString("Clientes"));
                    if ("24".equals(rs.getString("Clientes"))) {
                        btnCModificar.setBackground(Color.red);
                        stClienteModificar = "";
                    } else if ("2".equals(rs.getString("Clientes"))) {
                        btnCingresar.setBackground(Color.red);
                        btnCModificar.setBackground(Color.red);
                        btnCbusqueda.setBackground(Color.red);
                        stClienteBuscar = "";
                        stClienteIngresa = "";
                        stClienteModificar = "";
                    } else if ("0".equals(rs.getString("Clientes"))) {
                        btnCingresar.setBackground(Color.red);
                        btnCModificar.setBackground(Color.red);
                        btnClistar.setBackground(Color.red);
                        stClienteIngresa = "";
                        stClienteModificar = "";
                        stClienteListar = "";
                    } else if ("2479".equals(rs.getString("Clientes"))) {

                    } else if ("249".equals(rs.getString("Clientes"))) {
                        btnCModificar.setBackground(Color.red);
                        stClienteModificar = "";
                    } else if ("247".equals(rs.getString("Clientes"))) {
                        btnCbusqueda.setBackground(Color.red);
                        stClienteBuscar = "";
                    } else if ("29".equals(rs.getString("Clientes"))) {
                        btnCingresar.setBackground(Color.red);
                        btnCModificar.setBackground(Color.red);
                        stClienteIngresa = "";
                        stClienteModificar = "";
                    } else if ("27".equals(rs.getString("Clientes"))) {
                        btnCingresar.setBackground(Color.red);
                        btnCbusqueda.setBackground(Color.red);
                        stClienteIngresa = "";
                        stClienteBuscar = "";

                    }
                    //Proveedores
                    System.out.println(rs.getString("Proveedores"));
                    if ("24".equals(rs.getString("Proveedores"))) {
                        btnPmodificar.setBackground(Color.red);
                        stProveedorModificar = "";

                    } else if ("2".equals(rs.getString("Proveedores"))) {
                        btnPmodificar.setBackground(Color.red);
                        btnPingresar.setBackground(Color.red);
                        btnPbusqueda.setBackground(Color.red);
                        stProveedorBuscar = "";
                        stProveedorIngresa = "";
                        stProveedorModificar = "";
                    } else if ("0".equals(rs.getString("Proveedores"))) {
                        btnPingresar.setBackground(Color.red);
                        btnPmodificar.setBackground(Color.red);
                        btnPlistar.setBackground(Color.red);
                        stProveedorIngresa = "";
                        stProveedorModificar = "";
                        stProveedorListar = "";
                    } else if ("2479".equals(rs.getString("Proveedores"))) {

                    } else if ("249".equals(rs.getString("Proveedores"))) {
                        btnPmodificar.setBackground(Color.red);
                        stProveedorModificar = "";
                    } else if ("247".equals(rs.getString("Proveedores"))) {
                        btnPbusqueda.setBackground(Color.red);
                        stProveedorBuscar = "";
                    } else if ("29".equals(rs.getString("Proveedores"))) {
                        btnPingresar.setBackground(Color.red);
                        btnPmodificar.setBackground(Color.red);
                        stProveedorIngresa = "";
                        stProveedorModificar = "";
                    } else if ("27".equals(rs.getString("Proveedores"))) {
                        btnPingresar.setBackground(Color.red);
                        btnPbusqueda.setBackground(Color.red);
                        stProveedorIngresa = "";
                        stProveedorBuscar = "";

                    }
                    //Empleados

                    System.out.println(rs.getString("Empleados"));
                    String codEmpleado = "";

                    if (rs.getString("Empleados").contains("3")) {
                        codEmpleado = rs.getString("Empleados").substring(0, rs.getString("Empleados").length() - 1);
                    } else {
                        codEmpleado = rs.getString("Empleados");
                    }
                    System.out.println("el codigo de empleado es:" + codEmpleado);
                    if ("24".equals(codEmpleado)) {
                        btnEmodificar.setBackground(Color.red);
                        stEmpleadoModificar = "";

                    } else if ("2".equals(codEmpleado)) {
                        btnEingresar.setBackground(Color.red);
                        btnEmodificar.setBackground(Color.red);
                        btnEbusqueda.setBackground(Color.red);
                        stEmpleadoBuscar = "";
                        stEmpleadoIngresa = "";
                        stEmpleadoModificar = "";
                    } else if ("0".equals(codEmpleado)) {
                        btnEingresar.setBackground(Color.red);
                        btnEmodificar.setBackground(Color.red);
                        btnElistar.setBackground(Color.red);
                        stEmpleadoIngresa = "";
                        stEmpleadoModificar = "";
                        stEmpleadoListar = "";
                    } else if ("2479".equals(codEmpleado)) {

                    } else if ("249".equals(codEmpleado)) {
                        btnEmodificar.setBackground(Color.red);
                        stEmpleadoModificar = "";
                    } else if ("247".equals(codEmpleado)) {
                        btnEbusqueda.setBackground(Color.red);
                        stEmpleadoBuscar = "";
                    } else if ("29".equals(codEmpleado)) {
                        btnEingresar.setBackground(Color.red);
                        btnEmodificar.setBackground(Color.red);
                        stEmpleadoIngresa = "";
                        stEmpleadoModificar = "";
                    } else if ("27".equals(codEmpleado)) {
                        btnEingresar.setBackground(Color.red);
                        btnEbusqueda.setBackground(Color.red);
                        stEmpleadoIngresa = "";
                        stEmpleadoBuscar = "";

                    }
                    if (!rs.getString("Empleados").contains("3")) {
                        btnAddusers.setBackground(Color.red);
                        stEmpleadoAddUser = "";
                    }
                    //Productos

                    System.out.println(rs.getString("Productos"));
                    if ("24".equals(rs.getString("Productos"))) {
                        btnProModificar.setBackground(Color.red);
                        stProdModificar = "";
                        btnProdEliminar.setBackground(Color.red);
                        stProdEliminar = "";

                    } else if ("2".equals(rs.getString("Productos"))) {
                        btnProModificar.setBackground(Color.red);
                        btnProIngresar.setBackground(Color.red);
                        btnProdEliminar.setBackground(Color.red);
                        stProdEliminar = "";
                        stProdIngresa = "";
                        stProdModificar = "";
                    } else if ("0".equals(rs.getString("Productos"))) {
                        btnProIngresar.setBackground(Color.red);
                        btnProModificar.setBackground(Color.red);
                        btnProListar.setBackground(Color.red);
                        stProdIngresa = "";
                        stProdModificar = "";
                        stProdListar = "";
                    } else if ("2479".equals(rs.getString("Productos"))) {

                    } else if ("249".equals(rs.getString("Productos"))) {
                        btnProModificar.setBackground(Color.red);
                        stProdModificar = "";
                    } else if ("247".equals(rs.getString("Productos"))) {
                        btnProdEliminar.setBackground(Color.red);
                        stProdEliminar = "";
                    } else if ("29".equals(rs.getString("Productos"))) {
                        btnProIngresar.setBackground(Color.red);
                        btnProModificar.setBackground(Color.red);
                        stProdIngresa = "";
                        stProdModificar = "";
                    } else if ("27".equals(rs.getString("Productos"))) {
                        btnProIngresar.setBackground(Color.red);
                        btnProdEliminar.setBackground(Color.red);
                        stProdIngresa = "";
                        stProdEliminar = "";

                    }

                    ///CompraVenta
                    System.out.println(rs.getString("CompraVenta"));
                    if ("24".equals(rs.getString("CompraVenta"))) {
                        btnFacHf.setBackground(Color.red);
                        stFHistorialFacturacion = "";
                    } else if ("2".equals(rs.getString("CompraVenta"))) {
                        btnFacHv.setBackground(Color.red);
                        btnFacHf.setBackground(Color.red);
                        btnFacCompra.setBackground(Color.red);
                        stFHistorialVentas = "";
                        stFHistorialFacturacion = "";
                        stFCompra = "";
                    } else if ("0".equals(rs.getString("CompraVenta"))) {
                        btnFacVenta.setBackground(Color.red);
                        btnFacHv.setBackground(Color.red);
                        btnFacHf.setBackground(Color.red);
                        btnFacCompra.setBackground(Color.red);
                        stFVenta = "";
                        stFHistorialVentas = "";
                        stFHistorialFacturacion = "";
                        stFCompra = "";
                    } else if ("2479".equals(rs.getString("CompraVenta"))) {

                    } else if ("249".equals(rs.getString("CompraVenta"))) {
                        btnFacHf.setBackground(Color.red);
                        stFHistorialFacturacion = "";
                    } else if ("247".equals(rs.getString("CompraVenta"))) {
                        btnFacCompra.setBackground(Color.red);
                        stFCompra = "";
                    } else if ("29".equals(rs.getString("CompraVenta"))) {
                        btnFacHv.setBackground(Color.red);
                        btnFacHf.setBackground(Color.red);
                        stFHistorialVentas = "";
                        stFHistorialFacturacion = "";
                    } else if ("27".equals(rs.getString("CompraVenta"))) {
                        btnFacHv.setBackground(Color.red);
                        btnFacCompra.setBackground(Color.red);
                        stFHistorialVentas = "";
                        stFCompra = "";

                    } else if ("47".equals(rs.getString("CompraVenta"))) {
                        btnFacVenta.setBackground(Color.red);
                        btnFacCompra.setBackground(Color.red);
                        stFCompra = "";
                        stFVenta = "";
                    }
                    else if ("249".equals(rs.getString("CompraVenta"))) {
                        btnFacHv.setBackground(Color.red);
                       stFHistorialVentas = "";
                       
                    }
                     else if ("7".equals(rs.getString("CompraVenta"))) {
                        btnFacVenta.setBackground(Color.red);
                        btnFacHv.setBackground(Color.red);
                     
                        btnFacCompra.setBackground(Color.red);
                        stFVenta = "";
                        stFHistorialVentas = "";
                        
                        stFCompra = "";
                       
                    }

                    //otros
                    if ("24".equals(rs.getString("Otros"))) {

                    } else if ("4".equals(rs.getString("Otros"))) {
                        btnOconfiguracion.setBackground(Color.red);
                        stOconfiguracion = "";
                    } else if ("2".equals(rs.getString("Otros"))) {
                        btnOprecioHis.setBackground(Color.red);
                        stOprecioHis = "";
                    } else if ("0".equals(rs.getString("Otros"))) {
                        btnOconfiguracion.setBackground(Color.red);
                        btnOprecioHis.setBackground(Color.red);
                        stOconfiguracion = "";
                        stOprecioHis = "";
                    }

                }

            } else {
                JOptionPane.showMessageDialog(null, "El usuario no esta registrado", "Error", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }

    }//GEN-LAST:event_ClienteBuscarActionPerformed

    private void btnProListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProListarActionPerformed
        // TODO add your handling code here:
        if ("2".equals(stProdListar)) {
            btnProListar.setBackground(Color.red);
            stProdListar = "";
        } else {
            btnProListar.setBackground(Color.GREEN);
            stProdListar = "2";
        }
    }//GEN-LAST:event_btnProListarActionPerformed

    private void btnClistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClistarActionPerformed
        // TODO add your handling code here:

        if ("2".equals(stClienteListar)) {
            btnClistar.setBackground(Color.red);
            stClienteListar = "";

           
        } else {
            btnClistar.setBackground(Color.GREEN);
            stClienteListar = "2";
//             //------------
//            btnCingresar.setEnabled(true);
//            btnCModificar.setEnabled(true);
//            btnCbusqueda.setEnabled(true);
//
//            btnCingresar.setBackground(Color.red);
//            btnCModificar.setBackground(Color.red);
//            btnCbusqueda.setBackground(Color.red);
//
//            stClienteListar = "";
//            stClienteIngresa = "";
//            stClienteModificar = "";
//            stClienteBuscar = "";
        }

    }//GEN-LAST:event_btnClistarActionPerformed

    private void btnCingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCingresarActionPerformed
        // TODO add your handling code here:
        if (stClienteIngresa == "4") {
            btnCingresar.setBackground(Color.red);
            stClienteIngresa = "";
        } else {
            btnCingresar.setBackground(Color.GREEN);
            stClienteIngresa = "4";

        }
    }//GEN-LAST:event_btnCingresarActionPerformed

    private void btnCModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCModificarActionPerformed
        // TODO add your handling code here:
        if (stClienteModificar == "7") {
            btnCModificar.setBackground(Color.red);
            stClienteModificar = "";
        } else {
            btnCModificar.setBackground(Color.GREEN);
            stClienteModificar = "7";

        }
    }//GEN-LAST:event_btnCModificarActionPerformed

    private void btnPlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlistarActionPerformed
        // TODO add your handling code here:
        if ("2".equals(stProveedorListar)) {
            btnPlistar.setBackground(Color.red);
            stProveedorListar = "";
        } else {
            btnPlistar.setBackground(Color.GREEN);
            stProveedorListar = "2";
        }
        //

    }//GEN-LAST:event_btnPlistarActionPerformed

    private void btnPingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPingresarActionPerformed
        // TODO add your handling code here:
        if ("4".equals(stProveedorIngresa)) {
            btnPingresar.setBackground(Color.red);
            stProveedorIngresa = "";
        } else {
            btnPingresar.setBackground(Color.GREEN);
            stProveedorIngresa = "4";
        }
    }//GEN-LAST:event_btnPingresarActionPerformed

    private void btnPmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPmodificarActionPerformed
        // TODO add your handling code here:
        if ("7".equals(stProveedorModificar)) {
            btnPmodificar.setBackground(Color.red);
            stProveedorModificar = "";
        } else {
            btnPmodificar.setBackground(Color.GREEN);
            stProveedorModificar = "7";
        }
    }//GEN-LAST:event_btnPmodificarActionPerformed

    private void btnElistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElistarActionPerformed
        // TODO add your handling code here:
        if ("2".equals(stEmpleadoListar)) {
            btnElistar.setBackground(Color.red);
            stEmpleadoListar = "";
        } else {
            btnElistar.setBackground(Color.GREEN);
            stEmpleadoListar = "2";
        }
    }//GEN-LAST:event_btnElistarActionPerformed

    private void btnEingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEingresarActionPerformed
        // TODO add your handling code here:
        if ("4".equals(stEmpleadoIngresa)) {
            btnEingresar.setBackground(Color.red);
            stEmpleadoIngresa = "";
        } else {
            btnEingresar.setBackground(Color.GREEN);
            stEmpleadoIngresa = "4";
        }
    }//GEN-LAST:event_btnEingresarActionPerformed

    private void btnEmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmodificarActionPerformed
        // TODO add your handling code here:
        if ("7".equals(stEmpleadoModificar)) {
            btnEmodificar.setBackground(Color.red);
            stEmpleadoModificar = "";
        } else {
            btnEmodificar.setBackground(Color.GREEN);
            stEmpleadoModificar = "7";
        }
    }//GEN-LAST:event_btnEmodificarActionPerformed

    private void btnProIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProIngresarActionPerformed
        // TODO add your handling code here:
        if (stProdIngresa == "4") {
            btnProIngresar.setBackground(Color.red);
            stProdIngresa = "";
        } else {
            btnProIngresar.setBackground(Color.GREEN);
            stProdIngresa = "4";
        }
    }//GEN-LAST:event_btnProIngresarActionPerformed

    private void btnProModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProModificarActionPerformed
        // TODO add your handling code here:
        if (stProdModificar == "7") {
            btnProModificar.setBackground(Color.red);
            stProdModificar = "";
        } else {
            btnProModificar.setBackground(Color.GREEN);
            stProdModificar = "7";
        }
    }//GEN-LAST:event_btnProModificarActionPerformed
    public void clear() {
        lblnombre.setText("-----------");
        lblemail.setText("-----------");
        lbltelefono.setText("-----------");
        lblid.setText("-----------");
        lblpuesto.setText("-----------");
        jTabbedPane1.setEnabled(false);
        jTabbedPane1.setSelectedIndex(4);
        jButton1.setEnabled(false);
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String codCliente = stClienteListar + stClienteIngresa + stClienteModificar + stClienteBuscar;
        String codProveedor = stProveedorListar + stProveedorIngresa + stProveedorModificar + stProveedorBuscar;
        String codEmpleado = stEmpleadoListar + stEmpleadoIngresa + stEmpleadoModificar + stEmpleadoBuscar + stEmpleadoAddUser;
        String codProducto = stProdListar + stProdIngresa + stProdModificar + stProdEliminar;
        String CodCompraVenta = stFVenta + stFHistorialVentas + stFHistorialFacturacion + stFCompra;
        String codOtros = stOconfiguracion + stOprecioHis;

        if ("".equals(codCliente)) {
            codCliente = "0";
        }
        if ("".equals(codProveedor)) {
            codProveedor = "0";
        }
        if ("".equals(codEmpleado)) {
            codEmpleado = "0";
        }
        if ("".equals(codProducto)) {
            codProducto = "0";
        }
        if ("".equals(CodCompraVenta)) {
            CodCompraVenta = "0";
        }
        if ("".equals(codOtros)) {
            codOtros = "0";
        }

        System.out.println("Codigo generado a clientes: " + codCliente);
        System.out.println("Codigo generado a empleado: " + codEmpleado);
        System.out.println("Codigo generado a proveedor: " + codProveedor);
        System.out.println("Codigo generado a producto: " + codProducto);
        ConexionSQL cn = new ConexionSQL();
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        ///
        String sql = "SELECT EXISTS(SELECT * from usuariopermiso WHERE idUsuario=?) as usuario";
        try {

            con = cn.getConnection();
            ps = con.prepareStatement(sql);
            ps.setString(1, lblid.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                System.out.println(rs.getString("usuario"));
                if ("0".equals(rs.getString("usuario"))) {
                    try {

                        String sql2 = "INSERT INTO usuariopermiso  values (?,?,?,?,?,?,?) ";
                        con = cn.getConnection();
                        ps = con.prepareStatement(sql2);
                        ps.setString(1, lblid.getText());
                        ps.setString(2, codCliente);
                        ps.setString(3, codProveedor);
                        ps.setString(4, codEmpleado);
                        ps.setString(5, codProducto);
                        ps.setString(6, CodCompraVenta);
                        ps.setString(7, codOtros);
                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Guardado con exito");
                         jTabbedPane1.setSelectedIndex(6);

                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e.toString());

                    }
                } else {

                    try {
                        con = null;
                        ps = null;
                        rs = null;

                        String sql2 = "UPDATE `usuariopermiso` SET `Clientes`= ?,`Proveedores`=?,`Empleados`=?,`Productos`=?, `CompraVenta`=?, `Otros`=? WHERE`idUsuario`=?";
                        con = cn.getConnection();
                        ps = con.prepareStatement(sql2);

                        ps.setString(1, codCliente);
                        ps.setString(2, codProveedor);
                        ps.setString(3, codEmpleado);
                        ps.setString(4, codProducto);
                        ps.setString(5, CodCompraVenta);
                        ps.setString(6, codOtros);
                        ps.setString(7, lblid.getText());
                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Guardado con exito");
                         jTabbedPane1.setSelectedIndex(6);

                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e.toString());

                    }

                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
        clear();
        ClienteBuscar.setEnabled(true);
        jButton2.setEnabled(false);
        jTabbedPane1.setSelectedIndex(6);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        clear();
        stClienteListar = "2";
        stClienteIngresa = "4";
        stClienteModificar = "7";
        //Empleados
        stProveedorListar = "2";
        stProveedorIngresa = "4";
        stProveedorModificar = "7";
        //empleados
        stEmpleadoListar = "2";
        stEmpleadoIngresa = "4";
        stEmpleadoModificar = "7";
        //producto
        stProdListar = "1";
        stProdIngresa = "1";
        stProdModificar = "1";
        ClienteBuscar.setEnabled(true);
        jButton2.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCbusquedaActionPerformed
        // TODO add your handling code here:
        if ("9".equals(stClienteBuscar)) {
            btnCbusqueda.setBackground(Color.red);
            stClienteBuscar = "";
        } else {
            btnCbusqueda.setBackground(Color.GREEN);
            stClienteBuscar = "9";
        }
    }//GEN-LAST:event_btnCbusquedaActionPerformed

    private void btnPbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPbusquedaActionPerformed
        // TODO add your handling code here:
        if ("9".equals(stProveedorBuscar)) {
            btnPbusqueda.setBackground(Color.red);
            stProveedorBuscar = "";
        } else {
            btnPbusqueda.setBackground(Color.GREEN);
            stProveedorBuscar = "9";
        }
        //

    }//GEN-LAST:event_btnPbusquedaActionPerformed

    private void btnEbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEbusquedaActionPerformed
        // TODO add your handling code here:
        if (stEmpleadoBuscar == "9") {
            btnEbusqueda.setBackground(Color.red);
            stEmpleadoBuscar = "";
        } else {
            btnEbusqueda.setBackground(Color.GREEN);
            stEmpleadoBuscar = "9";
        }
    }//GEN-LAST:event_btnEbusquedaActionPerformed

    private void btnAddusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddusersActionPerformed
        // TODO add your handling code here:
        if ("3".equals(stEmpleadoAddUser)) {
            btnAddusers.setBackground(Color.red);
            stEmpleadoAddUser = "";
        } else {
            btnAddusers.setBackground(Color.GREEN);
            stEmpleadoAddUser = "3";
        }
    }//GEN-LAST:event_btnAddusersActionPerformed

    private void btnProdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdEliminarActionPerformed
        // TODO add your handling code here:
        if ("9".equals(stProdEliminar)) {
            btnProdEliminar.setBackground(Color.red);
            stProdEliminar = "";
        } else {
            btnProdEliminar.setBackground(Color.GREEN);
            stProdEliminar = "9";
        }
    }//GEN-LAST:event_btnProdEliminarActionPerformed

    private void btnFacVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacVentaActionPerformed
        // TODO add your handling code here:
        if ("2".equals(stFVenta)) {
            btnFacVenta.setBackground(Color.red);
            stFVenta = "";
        } else {
            btnFacVenta.setBackground(Color.GREEN);
            stFVenta = "2";
        }
    }//GEN-LAST:event_btnFacVentaActionPerformed

    private void btnFacHvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacHvActionPerformed
        // TODO add your handling code here:
        if ("4".equals(stFHistorialVentas)) {
            btnFacHv.setBackground(Color.red);
            stFHistorialVentas = "";
        } else {
            btnFacHv.setBackground(Color.GREEN);
            stFHistorialVentas = "4";
        }
    }//GEN-LAST:event_btnFacHvActionPerformed

    private void btnFacHfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacHfActionPerformed
        // TODO add your handling code here:
        if ("7".equals(stFHistorialFacturacion)) {
            btnFacHf.setBackground(Color.red);
            stFHistorialFacturacion = "";
        } else {
            btnFacHf.setBackground(Color.GREEN);
            stFHistorialFacturacion = "7";
        }
    }//GEN-LAST:event_btnFacHfActionPerformed

    private void btnFacCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacCompraActionPerformed
        // TODO add your handling code here:
        if ("9".equals(stFCompra)) {
            btnFacCompra.setBackground(Color.red);
            stFCompra = "";
        } else {
            btnFacCompra.setBackground(Color.GREEN);
            stFCompra = "9";
        }
    }//GEN-LAST:event_btnFacCompraActionPerformed

    private void btnOconfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOconfiguracionActionPerformed
        // TODO add your handling code here:
        if ("2".equals(stOconfiguracion)) {
            btnOconfiguracion.setBackground(Color.red);
            stOconfiguracion = "";
        } else {
            btnOconfiguracion.setBackground(Color.GREEN);
            stOconfiguracion = "2";
        }
    }//GEN-LAST:event_btnOconfiguracionActionPerformed

    private void btnOprecioHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOprecioHisActionPerformed
        // TODO add your handling code here:
        if ("4".equals(stOprecioHis)) {
            btnOprecioHis.setBackground(Color.red);
            stOprecioHis = "";
        } else {
            btnOprecioHis.setBackground(Color.GREEN);
            stOprecioHis = "4";
        }
    }//GEN-LAST:event_btnOprecioHisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSecurity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClienteBuscar;
    private javax.swing.JButton btnAddusers;
    private javax.swing.JButton btnCModificar;
    private javax.swing.JButton btnCbusqueda;
    private javax.swing.JButton btnCingresar;
    private javax.swing.JButton btnClistar;
    private javax.swing.JButton btnEbusqueda;
    private javax.swing.JButton btnEingresar;
    private javax.swing.JButton btnElistar;
    private javax.swing.JButton btnEmodificar;
    private javax.swing.JButton btnFacCompra;
    private javax.swing.JButton btnFacHf;
    private javax.swing.JButton btnFacHv;
    private javax.swing.JButton btnFacVenta;
    private javax.swing.JButton btnOconfiguracion;
    private javax.swing.JButton btnOprecioHis;
    private javax.swing.JButton btnPbusqueda;
    private javax.swing.JButton btnPingresar;
    private javax.swing.JButton btnPlistar;
    private javax.swing.JButton btnPmodificar;
    private javax.swing.JButton btnProIngresar;
    private javax.swing.JButton btnProListar;
    private javax.swing.JButton btnProModificar;
    private javax.swing.JButton btnProdEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpuesto;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
